"""Constantes partagees par l'interface Desktop."""

PAGE_DASHBOARD = "Tableau de bord"
PAGE_WEBSITES = "Websites"
PAGE_ENTITIES = "Entities"
PAGE_KEYWORDS = "Keywords"
PAGE_COMPETITORS = "Competitors"
PAGE_CRAWLS = "Crawls"
PAGE_GOOGLE_SEARCH_CONSOLE = "Google Search Console"
PAGE_GOOGLE_ANALYTICS = "Google Analytics 4"
PAGE_GEO_ANALYSIS = "GEO Analysis"
PAGE_SYNC_SCHEDULES = "Planifications"
PAGE_MONITORING = "Monitoring"
PAGE_ALERTS = "Alertes"
PAGE_PROJECT_TASKS = "Project Tasks"
PAGE_REPORTS = "Reports"
PAGE_ADMINISTRATION = "Administration"
PAGE_USERS = "Utilisateurs"

NAVIGATION_PAGES = [
    PAGE_DASHBOARD,
    PAGE_WEBSITES,
    PAGE_ENTITIES,
    PAGE_KEYWORDS,
    PAGE_COMPETITORS,
    PAGE_CRAWLS,
    PAGE_GOOGLE_SEARCH_CONSOLE,
    PAGE_GOOGLE_ANALYTICS,
    PAGE_GEO_ANALYSIS,
    PAGE_SYNC_SCHEDULES,
    PAGE_MONITORING,
    PAGE_ALERTS,
    PAGE_PROJECT_TASKS,
    PAGE_REPORTS,
    PAGE_ADMINISTRATION,
    PAGE_USERS,
]
